title: Hao Moy # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a mexican-american raised in Ciudad juarez, Mexico. Crossed the border by foot everyday to obtain my Computer Science degree from the University of Texas at El Paso. 
  <br>
  Passionate Microsoft program manager eager to learn what I can from anyone. 
  <br><br>
  <a href="https://www.linkedin.com/in/haomoy/">LinkedIn Profile</a> 
  <a href="https://github.com/haomoy">Github Profile</a> 
  
theme: jekyll-theme-minimal
